version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    environment:
      - PORT=${PORT:-3000}